### PR TITLE
[BC] Deprecated packages

### PR DESCRIPTION
**Pull request by imonteiro**
[container-interop-doctrine](https://github.com/DASPRiD/container-interop-doctrine) is deprecated => moved to [psr-container-doctrine](https://github.com/Roave/psr-container-doctrine).

[container-interop](https://github.com/container-interop/container-interop) is deprecated => moved to [psr-container](https://github.com/php-fig/container)

Note:
I will prepare PR to move SlmQueue to `psr-container`.

### CODE REVIEW

**Comment by roelvanduijnhoven** [comment]
@imonteiro Thanks: great work! Let me know once you want me to review your work!

**Comment by imonteiro** [comment]
Some notes:
- [BC] `roave/psr-container-doctrine` require PHP 7.3+.
- From `laminas-servicemanager` 3.3 it's supports `psr-container`. However, just in 4.0 the [FactoryInterface ](https://github.com/laminas/laminas-servicemanager/blob/bee72a96836b033c46dc4e0c0fa51e076ff2fafb/src/Factory/FactoryInterface.php)will be update - [documentation](https://docs.laminas.dev/laminas-servicemanager/psr-11/). Todo: create a issue to update `Interop\Container\ContainerInterface` to `Psr\Container\ContainerInterface` when `laminas-servicemanager` 4.0 is issued.

@roelvanduijnhoven @basz These changes could lead to a major release. Should we divide this PR on two PR, one for each package?

**Comment by roelvanduijnhoven** [comment]
@imonteiro I am find with bundling it in just this PR. Especially if that saves _you_ time.

We recently bumped our dependencies to PHP 7.2. But since 7.2 is end-of-life, I am fine with raising it yet again, and bumping the major version yet again. @basz What do you think?

**Comment by basz** [comment]
not eol just yet, but let's do it anyway

**Comment by roelvanduijnhoven** [comment]
@imonteiro This PR is open for some time now. 

I think we can merge this one, and release a new major version: right?

**Pull request closed without merging**
