### PR TITLE
Feature/laminas

### PR DESCRIPTION
**Pull request by basz**

### CODE REVIEW

**Comment by basz** [comment]
ugh, tests aren't running... ping @roelvanduijnhoven @juriansluiman

**Comment by basz** [comment]
nvm, there they go... :-)

**Comment by imonteiro** [comment]
According with [laminas-component-installer](https://github.com/laminas/laminas-component-installer) , we should change:

`"extra": {
  "zf": {`

to

`"extra": {
  "laminas": {`

**Comment by imonteiro** [comment]
@basz what you think add `slm/queue` package in "component-whitelist" to install automatically?

**Comment by basz** [comment]
I'm not aware of such a meganism. Seems great, I'll do that..

**Comment by basz** [comment]
what do you think bout those travis failures? ph74 and phpunit. seems we need a separate PR

**Comment by imonteiro** [comment]
Maybe the version of PHPUnit is too old, as it uses functions which were deprecated.
Dropping PHP 5 support and update PHPUnit 6 should solve these issues.

So yes, we need a separate PR .

**Comment by roelvanduijnhoven** [comment]
Nice work! Let me know if I can help with something.

**Comment by basz** [comment]
I wouldn't mind to drop php5 support... But I guess only if slm/queue does the same.

**Comment by roelvanduijnhoven** [comment]
@basz Sounds like a great move. What about we target for minimum version of PHP 7.2? That way we can utilize typing.

**Comment by basz** [comment]
Yes thank you!


I’ll be able to do doctrine-queue soon

**Comment by basz** [comment]
@roelvanduijnhoven can you merge please, I believe laminas migration would be done. I'll then create a new PR to update the php versions and phpunit

**Pull request merged**
